services:
  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "192.168.0.57:8000:8000"
    depends_on:
      - database
      - redis

  database:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=mac
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=energy-db
    ports:
      - "5432:5432"

  celery:
    build: .
    command: celery -A energy_monitoring worker --loglevel=info --concurrency=2
    volumes:
      - .:/app
    depends_on:
      - web
      - redis  # Ensure celery starts after redis

  celery-beat:
    build: .
    command: celery -A energy_monitoring beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"  # Expose Redis on port 6379
      
volumes:
  postgres_data: