# Generated by Django 5.1.1 on 2025-07-23 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computedvariable',
            name='conversion_factor',
            field=models.CharField(blank=True, default='1', help_text='Factor to convert raw data to physical value', null=True),
        ),
        migrations.AlterField(
            model_name='computedvariable',
            name='var_name',
            field=models.CharField(blank=True, help_text='Name of the variable (e.g., Voltage, Power)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dlmsmappingvariable',
            name='conversion_factor',
            field=models.CharField(blank=True, default='1', help_text='Factor to convert raw data to physical value', null=True),
        ),
        migrations.AlterField(
            model_name='dlmsmappingvariable',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dlms_variables', to='user_devices.device'),
        ),
        migrations.AlterField(
            model_name='dlmsmappingvariable',
            name='obis_code',
            field=models.CharField(blank=True, default='', help_text='Address of the mapped value', null=True),
        ),
        migrations.AlterField(
            model_name='dlmsmappingvariable',
            name='unit',
            field=models.CharField(blank=True, help_text='Measurement unit (e.g., V, A, W)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dlmsmappingvariable',
            name='var_name',
            field=models.CharField(blank=True, help_text='Name of the variable (e.g., Voltage, Power)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modbusmappingvariable',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Address of the mapped value', null=True),
        ),
        migrations.AlterField(
            model_name='modbusmappingvariable',
            name='conversion_factor',
            field=models.CharField(blank=True, default='1', help_text='Factor to convert raw data to physical value', null=True),
        ),
        migrations.AlterField(
            model_name='modbusmappingvariable',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modbus_variables', to='user_devices.device'),
        ),
        migrations.AlterField(
            model_name='modbusmappingvariable',
            name='unit',
            field=models.CharField(blank=True, help_text='Measurement unit (e.g., V, A, Hz)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modbusmappingvariable',
            name='var_name',
            field=models.CharField(blank=True, help_text='Name of the variable (e.g., Voltage, Power)', max_length=100, null=True),
        ),
    ]
