# Generated by Django 5.1.1 on 2025-07-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0002_alter_device_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='port',
            field=models.IntegerField(default=0),
        ),
    ]
