# Generated by Django 5.1.1 on 2025-09-18 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='is_device_active',
        ),
    ]
