# Generated by Django 5.1.1 on 2024-10-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0002_alter_device_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
