# Generated by Django 5.1.1 on 2024-10-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0002_modbusaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='modbusaddress',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='modbusaddress',
            name='address',
            field=models.IntegerField(default=0),
        ),
    ]
