# Generated by Django 5.1.1 on 2025-07-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0003_alter_device_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlmsmappingvariable',
            name='data_type',
            field=models.CharField(choices=[('clock', 'Clock'), ('profile', 'Profile')], default='clock', help_text='Select whether this variable is a clock or profile.', max_length=10),
        ),
        migrations.AddField(
            model_name='dlmsmappingvariable',
            name='days',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Number of days to retrieve (only for profile).', null=True),
        ),
    ]
