# Generated by Django 5.1.1 on 2024-11-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0003_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ssh_password',
            field=models.CharField(default='ssh_psw', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='ssh_username',
            field=models.CharField(default='ssh_user', max_length=50),
        ),
    ]
