# Generated by Django 5.1.1 on 2025-09-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0003_remove_device_is_device_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='availability',
            field=models.FloatField(default=0, help_text='Availability of the device'),
        ),
    ]
