# Generated by Django 5.1.1 on 2025-07-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0004_dlmsmappingvariable_data_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlmsmappingvariable',
            name='column_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of columns returned by OBIS block'),
        ),
        migrations.AddField(
            model_name='dlmsmappingvariable',
            name='column_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Unit and conversion factor per column, auto-filled by form'),
        ),
    ]
