# Generated by Django 5.1.1 on 2024-11-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0004_device_ssh_password_device_ssh_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_records',
            field=models.IntegerField(default=10),
        ),
    ]
