# Generated by Django 5.1.1 on 2025-09-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0004_device_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='daily_consumption',
            field=models.FloatField(default=0, help_text='Daily consumption of the device'),
        ),
        migrations.AddField(
            model_name='device',
            name='daily_production',
            field=models.FloatField(default=0, help_text='Daily production of the device'),
        ),
        migrations.AddField(
            model_name='gateway',
            name='availability',
            field=models.FloatField(default=0, help_text='Availability of the plant'),
        ),
        migrations.AddField(
            model_name='gateway',
            name='consumption',
            field=models.FloatField(default=0, help_text='Consumption of the plant'),
        ),
        migrations.AddField(
            model_name='gateway',
            name='performance',
            field=models.FloatField(default=0, help_text='Performance of the plant'),
        ),
        migrations.AddField(
            model_name='gateway',
            name='performance_factor',
            field=models.FloatField(default=0, help_text='Performance factor of the plant'),
        ),
        migrations.AddField(
            model_name='gateway',
            name='production',
            field=models.FloatField(default=0, help_text='Production of the plant'),
        ),
    ]
