# Generated by Django 5.1.1 on 2025-09-18 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0005_device_daily_consumption_device_daily_production_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='Gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_device_data', to='user_devices.gateway'),
        ),
        migrations.CreateModel(
            name='GatewayData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_data', to='user_devices.gateway')),
                ('user', models.ManyToManyField(related_name='user_gateway_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
