# Generated by Django 5.1.1 on 2025-07-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0005_dlmsmappingvariable_column_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dlmsmappingvariable',
            name='column_count',
        ),
        migrations.RemoveField(
            model_name='dlmsmappingvariable',
            name='column_metadata',
        ),
        migrations.RemoveField(
            model_name='dlmsmappingvariable',
            name='days',
        ),
        migrations.AddField(
            model_name='device',
            name='days',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Number of days to retrieve (only for profile).', null=True),
        ),
    ]
