# Generated by Django 5.1.1 on 2024-12-14 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0005_device_last_records'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modbusaddress',
            name='device',
        ),
        migrations.RemoveField(
            model_name='device',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='device',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='device',
            name='last_records',
        ),
        migrations.RemoveField(
            model_name='device',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='device',
            name='mac_address',
        ),
        migrations.RemoveField(
            model_name='device',
            name='port',
        ),
        migrations.RemoveField(
            model_name='device',
            name='ssh_password',
        ),
        migrations.RemoveField(
            model_name='device',
            name='ssh_username',
        ),
        migrations.AddField(
            model_name='device',
            name='bytes_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='device',
            name='slave_id',
            field=models.IntegerField(default=-1, unique=True),
        ),
        migrations.AddField(
            model_name='device',
            name='start_address',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_device', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssh_username', models.CharField(default='ssh_user', max_length=50)),
                ('ssh_password', models.CharField(default='ssh_psw', max_length=100)),
                ('ip_address', models.CharField(max_length=50)),
                ('port', models.IntegerField(default=502)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_gateway', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='Gateway',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='user_devices.gateway'),
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_name', models.CharField(help_text='Name of the variable (e.g., Voltage - L1)', max_length=100)),
                ('address', models.PositiveIntegerField(help_text='Starting Modbus address in hexadecimal (e.g., 280h)')),
                ('bytes_count', models.PositiveIntegerField(default=1, help_text='Number of bytes to read')),
                ('unit', models.CharField(help_text='Measurement unit (e.g., V, A, Hz)', max_length=20)),
                ('conversion_factor', models.FloatField(default=1.0, help_text='Factor to convert raw data to physical value')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_mappings', to='user_devices.device')),
            ],
        ),
        migrations.DeleteModel(
            name='DeviceData',
        ),
        migrations.DeleteModel(
            name='ModbusAddress',
        ),
    ]
