# Generated by Django 5.1.1 on 2024-12-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0006_remove_modbusaddress_device_remove_device_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='address',
            field=models.CharField(help_text='Starting Modbus address in hexadecimal (e.g., 0x0280)'),
        ),
    ]
