# Generated by Django 5.1.1 on 2025-09-19 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0006_alter_devicedata_gateway_gatewaydata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='button',
            options={'ordering': ['label'], 'verbose_name': 'Button', 'verbose_name_plural': 'Buttons'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['name'], 'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterModelOptions(
            name='devicedata',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Device Data', 'verbose_name_plural': 'Device Data'},
        ),
        migrations.AlterModelOptions(
            name='energydata',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Energy Data', 'verbose_name_plural': 'Energy Data'},
        ),
        migrations.AlterModelOptions(
            name='gateway',
            options={'ordering': ['name'], 'verbose_name': 'Gateway', 'verbose_name_plural': 'Gateways'},
        ),
        migrations.AlterModelOptions(
            name='gatewaydata',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Gateway Data', 'verbose_name_plural': 'Gateway Data'},
        ),
    ]
