# Generated by Django 5.1.1 on 2025-07-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0006_remove_dlmsmappingvariable_column_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='days',
        ),
        migrations.RemoveField(
            model_name='dlmsmappingvariable',
            name='data_type',
        ),
        migrations.AddField(
            model_name='dlmsmappingvariable',
            name='column_idx',
            field=models.IntegerField(default=1, help_text='Column of the profile generic to read'),
        ),
    ]
