# Generated by Django 5.1.1 on 2025-09-19 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0007_alter_button_options_alter_device_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gateway',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='gateway',
            name='consumption',
        ),
        migrations.RemoveField(
            model_name='gateway',
            name='performance',
        ),
        migrations.RemoveField(
            model_name='gateway',
            name='production',
        ),
    ]
