# Generated by Django 5.1.1 on 2024-12-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0007_alter_mapping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='bytes_count',
            field=models.PositiveIntegerField(default=1, help_text='Total number of consecutive bytes to read'),
        ),
        migrations.AlterField(
            model_name='device',
            name='slave_id',
            field=models.IntegerField(default=-1, help_text='Salve ID of the device(nr between 1 to 247)', unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='start_address',
            field=models.CharField(help_text='Starting Modbus address in hexadecimal (e.g., 0x0280)'),
        ),
    ]
