# Generated by Django 5.1.1 on 2025-08-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0007_remove_device_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedvariable',
            name='show_in_homepage',
            field=models.BooleanField(default=False, help_text='Show this variable in the homepage'),
        ),
        migrations.AddField(
            model_name='dlmsmappingvariable',
            name='show_in_homepage',
            field=models.BooleanField(default=False, help_text='Show this variable in the homepage'),
        ),
        migrations.AddField(
            model_name='modbusmappingvariable',
            name='show_in_homepage',
            field=models.BooleanField(default=False, help_text='Show this variable in the homepage'),
        ),
    ]
