# Generated by Django 5.1.1 on 2025-08-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0008_computedvariable_show_in_homepage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_device_active',
            field=models.BooleanField(default=False, help_text='Does the device also produce energy?'),
        ),
    ]
