# Generated by Django 5.1.1 on 2025-09-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0008_remove_gateway_availability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='bytes_count',
        ),
        migrations.AddField(
            model_name='device',
            name='word_count',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Total number of consecutive words to read', null=True),
        ),
    ]
