# Generated by Django 5.1.1 on 2025-09-08 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0009_device_is_device_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_energy_data', to='user_devices.gateway')),
                ('device_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_data', to='user_devices.device')),
                ('user', models.ManyToManyField(related_name='user_energy_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
