# Generated by Django 5.1.1 on 2025-09-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0009_remove_device_bytes_count_device_word_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='modbusmappingvariable',
            name='endianness',
            field=models.CharField(choices=[('big', 'Big Endian'), ('little', 'Little Endian')], default='big', help_text='Endianness of the register (Big Endian or Little Endian)', max_length=10),
        ),
    ]
