# Generated by Django 5.1.1 on 2024-12-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0010_alter_device_slave_id_computedvariable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computedvariable',
            name='formula',
            field=models.TextField(help_text="Formula to calculate the value (e.g., 'voltage * current'). Variables must match existing MemoryMapping variable names"),
        ),
        migrations.AlterField(
            model_name='mappingvariable',
            name='bytes_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of words to read'),
        ),
    ]
