# Generated by Django 5.1.1 on 2025-10-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0010_modbusmappingvariable_endianness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatewaydata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
