# Generated by Django 5.1.1 on 2025-11-23 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0011_alter_gatewaydata_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome della sezione (es. Power, MPPT, Stato)', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordine di visualizzazione della sezione')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_sections', to='user_devices.device')),
            ],
            options={
                'verbose_name': 'Counter Section',
                'verbose_name_plural': 'Counter Sections',
                'ordering': ['device', 'order', 'name'],
                'unique_together': {('device', 'name')},
            },
        ),
        migrations.AddField(
            model_name='computedvariable',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Sezione logica per raggruppare questo counter', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_variables', to='user_devices.countersection'),
        ),
        migrations.AddField(
            model_name='dlmsmappingvariable',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Sezione logica per raggruppare questo counter', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_variables', to='user_devices.countersection'),
        ),
        migrations.AddField(
            model_name='modbusmappingvariable',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Sezione logica per raggruppare questo counter', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_variables', to='user_devices.countersection'),
        ),
    ]
