# Generated by Django 5.1.1 on 2024-12-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0012_alter_mappingvariable_bytes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
