# Generated by Django 5.1.1 on 2024-12-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0016_devicedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappingvariable',
            name='end_index',
        ),
        migrations.RemoveField(
            model_name='mappingvariable',
            name='start_index',
        ),
        migrations.AddField(
            model_name='mappingvariable',
            name='address',
            field=models.CharField(default='', help_text='Address of the mapped value'),
        ),
    ]
