# Generated by Django 5.1.1 on 2024-12-31 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0019_alter_userdatapreference_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedvariable',
            name='is_x_axis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='computedvariable',
            name='is_y_axis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mappingvariable',
            name='is_x_axis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mappingvariable',
            name='is_y_axis',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='UserDataPreference',
        ),
    ]
