# Generated by Django 5.1.1 on 2024-12-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0020_computedvariable_is_x_axis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computedvariable',
            name='is_x_axis',
        ),
        migrations.RemoveField(
            model_name='computedvariable',
            name='is_y_axis',
        ),
        migrations.RemoveField(
            model_name='mappingvariable',
            name='is_x_axis',
        ),
        migrations.RemoveField(
            model_name='mappingvariable',
            name='is_y_axis',
        ),
        migrations.AddField(
            model_name='computedvariable',
            name='show_on_graph',
            field=models.BooleanField(default=False, help_text='Show this variable on the graph'),
        ),
        migrations.AddField(
            model_name='mappingvariable',
            name='show_on_graph',
            field=models.BooleanField(default=False, help_text='Show this variable on the graph'),
        ),
    ]
