# Generated by Django 5.1.1 on 2025-04-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0022_alter_device_slave_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gateway',
            name='port',
        ),
        migrations.AddField(
            model_name='device',
            name='port',
            field=models.IntegerField(default=502),
        ),
    ]
