# Generated by Django 5.1.1 on 2025-04-05 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0023_remove_gateway_port_device_port'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='user',
        ),
        migrations.RemoveField(
            model_name='devicedata',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gateway',
            name='user',
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ManyToManyField(related_name='user_device', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicedata',
            name='user',
            field=models.ManyToManyField(related_name='user_device_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gateway',
            name='user',
            field=models.ManyToManyField(related_name='user_gateway', to=settings.AUTH_USER_MODEL),
        ),
    ]
