# Generated by Django 5.1.1 on 2025-04-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0024_remove_device_user_remove_devicedata_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicedata',
            old_name='gateway',
            new_name='Gateway',
        ),
    ]
