# Generated by Django 5.1.1 on 2025-04-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0025_rename_gateway_devicedata_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='name',
            field=models.CharField(default='not assigned', max_length=50),
        ),
    ]
