# Generated by Django 5.1.1 on 2025-04-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0026_gateway_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computedvariable',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='mappingvariable',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='computedvariable',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mappingvariable',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
