# Generated by Django 5.1.1 on 2025-04-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0027_alter_computedvariable_options_alter_device_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='show_energy',
            field=models.BooleanField(default=False, help_text='Show real time energy production/consumption'),
        ),
        migrations.AddField(
            model_name='device',
            name='show_energy_daily',
            field=models.BooleanField(default=False, help_text='Show daily energy production/consumption'),
        ),
        migrations.AddField(
            model_name='device',
            name='show_energy_monthly',
            field=models.BooleanField(default=False, help_text='Show monthly energy production/consumption'),
        ),
        migrations.AddField(
            model_name='device',
            name='show_energy_weekly',
            field=models.BooleanField(default=False, help_text='Show weekly energy production/consumption'),
        ),
    ]
