# Generated by Django 5.1.1 on 2025-06-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0028_device_show_energy_device_show_energy_daily_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingvariable',
            name='bit_length',
            field=models.PositiveIntegerField(choices=[(16, '16 bit'), (32, '32 bit'), (64, '64 bit')], default=16, help_text='Bit length of the register (16, 32, 64)'),
        ),
        migrations.AddField(
            model_name='mappingvariable',
            name='is_signed',
            field=models.BooleanField(default=False, help_text='Interpret value as signed (True) or unsigned (False)'),
        ),
    ]
