# Generated by Django 5.1.1 on 2025-07-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0029_mappingvariable_bit_length_mappingvariable_is_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='register_type',
            field=models.CharField(choices=[('input', 'Input Register'), ('holding', 'Holding Register')], default='input', help_text='Type of Modbus register to read (Input or Holding)', max_length=10),
        ),
    ]
