# Generated by Django 5.1.1 on 2025-07-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0030_device_register_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_enabled',
            field=models.BooleanField(default=False, help_text='Enable/Disable monitoring for this device'),
        ),
    ]
