# Generated by Django 5.1.1 on 2025-07-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0031_device_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='protocol',
            field=models.CharField(choices=[('modbus', 'MODBUS'), ('dlms', 'DLMS')], default='modbus', help_text='Type of protocol for the readings', max_length=10),
        ),
    ]
