# Generated by Django 5.1.1 on 2025-07-22 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0032_device_protocol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='protocol',
        ),
    ]
