# Generated by Django 5.1.1 on 2025-07-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_devices', '0034_device_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='start_address',
            field=models.CharField(default=0, help_text='Starting Modbus address in hexadecimal (e.g., 0x0280)'),
        ),
    ]
